language: node_js

sudo: required

dist: xenial

node_js: stable

branches:
    only:
        - hexo

before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli

install:
    - npm install

script:
    - hexo clean
    - hexo generate

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: public
    name: $GIT_NAME
    email: $GIT_EMAIL
    github_token: $GITHUB_TOKEN
    keep-history: true
    target-branch: master
    on:
        branch: hexo
